fix(dns): database hostname not resolved #14 #27 #30
Since docker v1.10 (and docker-compose v2), all containers use embedded DNS server to resolve
the IP addresses of others containers but postfix couldn't access this dns server inside his
own chroot.

diff --git a/rootfs/usr/local/bin/startup b/rootfs/usr/local/bin/startup
--- a/rootfs/usr/local/bin/startup
+++ b/rootfs/usr/local/bin/startup
@@ -179,6 +179,23 @@ else
   echo "[INFO] No extra postfix settings loaded because optional custom configuration file (/var/mail/postfix/custom.conf) is not provided."
 fi
 
+# Check database hostname
+grep -q "${DBHOST}" /etc/hosts
+
+if [ $? -ne 0 ]; then
+  echo "[INFO] Database hostname not found in /etc/hosts, try to find container IP with docker embedded DNS server"
+  IP=$(dig A ${DBHOST} +short)
+  if [ -n "$IP" ]; then
+    echo "[INFO] Container IP found, adding new record in /etc/hosts"
+    echo "${IP} ${DBHOST}" >> /etc/hosts
+  else
+    echo "[ERROR] Container IP not found with embedded DNS server... Abort !"
+    exit 1
+  fi
+else
+  echo "[INFO] Database hostname found in /etc/hosts"
+fi
+
 # AMAVIS TUNING
 # ---------------
 # Set Amavis maximun number of child processes (2 Childs/Core)
